[workspace]
members = ["tryphon", "tryphon_macros", "tryphon_examples"]
resolver = "3"

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/katlasik/tryphon"
homepage = "https://github.com/katlasik/tryphon"