[package]
name = "tryphon_examples"
version.workspace = true
edition.workspace = true
license.workspace = true

description = "Examples of tryphon configuration library"

publish = false

[dependencies]
tryphon = { path = "../tryphon" }